// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type Actor struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	MovieImdbIds []string  `json:"movieImdbIds"`
	ImdbID       string    `json:"imdbId"`
}

func (Actor) IsEntity() {}

type Query struct {
}
