// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package dataloaders

import (
	"sync"
	"time"

	"github.com/jtomasevic/go-graphql-federation-demo/movies/services/movies"
)

// MoviesLoaderConfig captures the config to create a new MoviesLoader
type MoviesLoaderConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []string) ([][]movies.Movie, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewMoviesLoader creates a new MoviesLoader given a fetch, wait, and maxBatch
func NewMoviesLoader(config MoviesLoaderConfig) *MoviesLoader {
	return &MoviesLoader{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// MoviesLoader batches and caches requests
type MoviesLoader struct {
	// this method provides the data for the loader
	fetch func(keys []string) ([][]movies.Movie, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[string][]movies.Movie

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *moviesLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type moviesLoaderBatch struct {
	keys    []string
	data    [][]movies.Movie
	error   []error
	closing bool
	done    chan struct{}
}

// Load a Movie by key, batching and caching will be applied automatically
func (l *MoviesLoader) Load(key string) ([]movies.Movie, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a Movie.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *MoviesLoader) LoadThunk(key string) func() ([]movies.Movie, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() ([]movies.Movie, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &moviesLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() ([]movies.Movie, error) {
		<-batch.done

		var data []movies.Movie
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *MoviesLoader) LoadAll(keys []string) ([][]movies.Movie, []error) {
	results := make([]func() ([]movies.Movie, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	movies := make([][]movies.Movie, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		movies[i], errors[i] = thunk()
	}
	return movies, errors
}

// LoadAllThunk returns a function that when called will block waiting for a Movies.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *MoviesLoader) LoadAllThunk(keys []string) func() ([][]movies.Movie, []error) {
	results := make([]func() ([]movies.Movie, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([][]movies.Movie, []error) {
		movies := make([][]movies.Movie, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			movies[i], errors[i] = thunk()
		}
		return movies, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *MoviesLoader) Prime(key string, value []movies.Movie) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
		// and end up with the whole cache pointing to the same value.
		cpy := make([]movies.Movie, len(value))
		copy(cpy, value)
		l.unsafeSet(key, cpy)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *MoviesLoader) Clear(key string) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *MoviesLoader) unsafeSet(key string, value []movies.Movie) {
	if l.cache == nil {
		l.cache = map[string][]movies.Movie{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *moviesLoaderBatch) keyIndex(l *MoviesLoader, key string) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *moviesLoaderBatch) startTimer(l *MoviesLoader) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *moviesLoaderBatch) end(l *MoviesLoader) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
