// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package services

import (
	"github.com/jtomasevic/go-graphql-federation-demo/movies/services/movies"
	"github.com/jtomasevic/go-graphql-federation-demo/movies/services/movies/data_source"
)

// Injectors from wire.go:

func InilizeServices() *Services {
	dataSourceService := datasource.NewDataSource()
	movieRepo := movies.NewDataStore(dataSourceService)
	movieService := movies.NewService(movieRepo)
	services := &Services{
		MovieService: movieService,
	}
	return services
}
