package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"

	"github.com/jtomasevic/go-graphql-federation-demo/actors/graph"
	"github.com/jtomasevic/go-graphql-federation-demo/actors/graph/model"
)

// FindActorByImdbID is the resolver for the findActorByImdbID field.
func (r *entityResolver) FindActorByImdbID(ctx context.Context, imdbID string) (model.Actor, error) {
	fmt.Printf("actor->entityResolver->FindActorByImdbID name:%s\n", imdbID)
	actor, err := r.Services.ActorService.GetActorByImdbID(ctx, imdbID)
	if err != nil {
		return model.Actor{}, err
	}
	return model.Actor(actor), nil
}

// Entity returns graph.EntityResolver implementation.
func (r *Resolver) Entity() graph.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
