// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type Actor struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	MovieImdbIds []string  `json:"movieImdbIds"`
	ImdbID       string    `json:"imdbId"`
	Movies       []Movie   `json:"movies"`
}

func (Actor) IsEntity() {}

type Movie struct {
	ID     uuid.UUID `json:"id"`
	Title  string    `json:"title"`
	ImdbID string    `json:"imdbId"`
}

type Query struct {
}
